# Generated by Django 5.0.2 on 2024-05-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
